dataset_name: example_tiny
version: 1
protocol_version: 1
random_seed: 2026
split_name: toy_split
split_description: minimal benchmark example
reference_h5ad: /path/to/reference.h5ad
query_h5ad: /path/to/query.h5ad
label_columns:
  - anno_lv1
coord_targets:
  latent: X_ref_latent
  umap: X_umap
train:
  num_epochs: 1
  batch_size: 64
  hidden_sizes: [8]
predict:
  knn_correction: low_conf_only
  batch_size: 128
